### ISSUE TITLE
wrong username/passwd

### ISSUE THREAD

**Issue by 8l4ckout** [JuanuSt/mmega#1]
I am sure, that username and password are correct. Megatools work just fine with it. But i have issues to connect with mmega.sh and mmega_cron.sh

This is config file:
`Movies,_EMAIL_,_PASSWORD_,"_LOCALPATH_","_REMOTE_PATH_"`

**Comment by JuanuSt** [comment]
Hi, thanks to report.

I 'm sorry, but I think that the problem is due to binaries. The version that I loaded was for raspberry, and the megatools binaries are in /usr/local/bin/megaXX, however in ubuntu are in /usr/bin/megaXX.

You can check the path to the binaries with:
`which megals`
`which megacopy`

Then you can change the lines 94 and 95: 
`94 MEGADF=/your/path/megadf`
`95 MEGACOPY=/your/path/megacopy`

Or
`94 MEGADF=$(which megals)`
`95 MEGACOPY=$(which megacopy)`

If it doesn't work, let me know.

EDIT:
I just realized, that you don't need quotation marks in any field. Try again removing quotation marks from local and remote directories.

I Movies,_EMAIL_,_PASSWORD_,_LOCALPATH_,_REMOTE_PATH_
