### ISSUE TITLE
Keep Getting file not valid

### ISSUE THREAD

**Issue by Ryahn** [JuanuSt/mmega#2]
I have a text file with the following

`nickname,EMAIL,PASS`
 
I have also tried
`nickname,EMAIL,PASS,,`

Also note, my passwords have special characters in them (!$%#)

```
   MEGAtools multi-account ⓚ                                      v.0.9
                                                       21:55 ⌚ 29.08.18
[+] Host stage
[-] File not valid [accounts.txt]

ryahn@stage:~$
```

**Comment by JuanuSt** [comment]
Hi, thanks to report.

You will have to give local and remote directories. If you don't have / need local directory you will have to create a empty directory and write it in config file. For the remote directory you have to use '/Root'.

This error is due to parsing checks in the script, if there are not directories the file is considered not valid.

**Comment by Ryahn** [comment]
Sorry for the really late reply. That fixed the issue. Thank you
